domain: "massa.network"
network_node_url: "https://buildnet.massa.net/api/v2"
api_port: 8080
allow_list:
  - "massaNameService"
  - ""
block_list:
  - "massaNameService"
  - "AS12g3GBGCEUdDdSyX7H2iyazwTFTfheRgWZuLuCTYKnTdsDCUsHX"
misc_public_info: {
  "tips": {
    "BTC": "1PMyg9yJe9Y8zS3bD2N4e6w2F7K6Rmyt7B",
    "ETH": "0x71C7656EC7ab88b098defB751B7401B5f6d8976F",
    "MAS": "AU1wfDH3BNBiFF9Nwko6g8q5gMzHW8KUHUL2YysxkZKNZHq37AfX"
  }
}